### ISSUE TITLE
Odometry error propagation example: Wheelbase not included

### ISSUE THREAD

**Issue by mmichini** [Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots#21]
The delta theta line in equation referenced below should include the wheelbase (distance between the two wheels) in the denominator, i.e., it should read `\Delta \theta &=& \frac{\Delta s_r-\Delta s_l}{b}` where `b` is the wheelbase.

https://github.com/correll/Introduction-to-Autonomous-Robots/blob/2eb825da7021bdc06517631d0ed2c86bbac177fe/chapters/errorpropagation.tex#L77

**Comment by correll** [comment]
I agree, thanks for pointing it out!
