### ISSUE TITLE
Trying to get my local compilation straight

### ISSUE THREAD

**Issue by alecive** [Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots#23]
I was looking at this issue https://github.com/correll/Introduction-to-Autonomous-Robots/issues/22 but I don’t seem to find equation 8.12 in my local compiled version of the book. @correll have you shuffled things around or am I missing some files/stuff ? 

FYI I am compiling with `pdflatex book.tex` on WSL Ubuntu. I get a bunch of warnings and citations are missingbut they are too many to list, but the generated PDF is 227 pages long so it seems to be working fine. Is the issue above obsolete because of new updates?

**Comment by correll** [comment]
Chapters have changed so 8.12 is now 9.12. Will be fixed soon!
