### ISSUE TITLE
configuration space of 2-DOF arm

### ISSUE THREAD

**Issue by goekce** [Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots#31]
![](https://github.com/correll/Introduction-to-Autonomous-Robots/raw/master/figs/fwk2dofarm.png)

The configuration space for the first link is

<img src="https://latex.codecogs.com/svg.latex?0<\alpha<\pi" />

and not (as given in chapter 3.2.1):

<img src="https://latex.codecogs.com/svg.latex?\frac{-\pi}{2}<\alpha<\frac{\pi}{2}" />

Does it make sense?

**Comment by correll** [comment]
I would agree
