### ISSUE TITLE
Path planning: obstacles are grown by *half* of the longest extension from the origin?

### ISSUE THREAD

**Issue by goekce** [Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots#33]
Dear Nikolaus,

from path planning chapter:

> ... all the obstacles in the environment are grown by half of the longest extension of the robot from its center.

Shouldn't we grow the obstacles simply by the full length of the longest extension from robot's *origin*?

![](https://raw.githubusercontent.com/correll/Introduction-to-Autonomous-Robots/master/figs/configurationspace.png)

Here is another example:

http://www.cs.columbia.edu/~allen/F17/NOTES/lozanogrown.pdf#page=6

**Comment by correll** [comment]
I don’t really understand the approach they are using. It also seems they don’t grow the object into every direction. Maybe it is computationally simpler than my approach when considering vector objects. 

I drew over their example to explain my approach.



I think at the end its just about the concept of C-space and growing a grid map can be done with a dilation operation.

Best,
Nikolaus

**Comment by goekce** [comment]
> I don’t really understand the approach they are using. It also seems they don’t grow the object into every direction. Maybe it is computationally simpler than my approach when considering vector objects.

I think they assume that the robot (object) never rotates.

> I drew over their example to explain my approach.

I cannot see any drawing.

> I think at the end its just about the concept of C-space and growing a grid map can be done with a dilation operation.

Makes sense.

Actually my point was more about the wording in your example:

> are grown by *half* of the longest extension of the robot *from its center*.

Shouldn't we rather say: In the figure the obstacles are grown by the *longest extension from its center*.

**Comment by correll** [comment]
I agree on the wording!
