### ISSUE TITLE
Save all SVG images as PDF

### ISSUE THREAD

**Issue by correll** [Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots#35]
Make sure page size is adjusted to content

**Comment by correll** [comment]
Make sure page size is adjusted to content

**Comment by alecive** [comment]
This https://castel.dev/post/lecture-notes-2/  is a pretty good tutorial on how to convert to tkiz (from @crheckman )

**Comment by alecive** [comment]
Please see here for my first test: https://github.com/correll/Introduction-to-Autonomous-Robots/commit/34d1659cebb67d5afd27ee5d2c7ec6f563c54861

It seems to be working great! Now the figures are using the same font as the text and I really like it: 

![image](https://user-images.githubusercontent.com/4378663/103570084-ac1b0180-4e85-11eb-883f-3750d839571a.png)

**Comment by alecive** [comment]
For the record: please remember to force-add the PDF file of the figure!

**Comment by alecive** [comment]
See this commit https://github.com/correll/Introduction-to-Autonomous-Robots/commit/f7c88e2f9ff636e6fdbca4509b0d0b0cdcfc8ba2 for a way to add equations to the inkscape fig.

**Comment by alecive** [comment]
I finished converting all pictures in the kinematics chapter. It was a drag, but it looks great!

**Comment by alecive** [comment]
Update: finished with the kinematics chapter with https://github.com/Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots/commit/8c139c4b930e278056ad98bd03478d8e88bec6e0

**Comment by alecive** [comment]
@correll @crheckman @hayesbh I gave all the chapters a pass. All figures are converted to PDF except from those in https://github.com/Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots/issues/60. If you create new figures, please export them to PDF directly using the tutorial above. I'm closing this for now.
