### ISSUE TITLE
Vision chapter needs to be better integrated into sensing

### ISSUE THREAD

**Issue by correll** [Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots#48]
The Vision chapter is at an odd place between sensing and computation. If it stays in the sensors part, we should modify language slightly and make clear that all of the computation in this chapter falls into the category "signal processing". 

I believe that makes sense as a lot of the sensors, e.g. Lidar, Stereo vision etc, that we describe have a significant computational component that is usually shielded from the roboticist. A related idea is to rename that part "Sensing and signal processing".

**Comment by crheckman** [comment]
I will handle.

**Comment by alecive** [comment]
Reopening: you will handle or you did handle? 😎

**Comment by crheckman** [comment]
Having two to-do lists is redundant and there's already #51, so I consolidated.
