### ISSUE TITLE
Link to PDF?

### ISSUE THREAD

**Issue by TylerL-uxai** [Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots#5]
Hi, how do I read the PDF? Is there a url somewhere?

**Comment by correll** [comment]
Its available via the "releases" tab

**Comment by as1ndu** [comment]
Here is the link to the [PDF](https://github.com/correll/Introduction-to-Autonomous-Robots/releases/download/v1.7/book.pdf)
