### ISSUE TITLE
Formula 9.4 page 148

### ISSUE THREAD

**Issue by CL-BZH** [Introduction-to-Autonomous-Robots/Introduction-to-Autonomous-Robots#50]
Hello,

Could it be that there is an error in formula 9.4.
P(loc|odo)=\sum_{loc'}P(loc'->loc)P(odo|loc'->loc).
I guess it comes from P(loc|odo)=\sum_{loc'}P(loc'->loc|odo).
And P(loc'->loc|odo) is replaced by equation 9.2
P(loc'->loc|odo)=P(loc'->loc)P(odo|loc'->loc)/P(odo).
Which gives
P(loc|odo)=\sum_{loc'}P(loc'->loc)P(odo|loc'->loc)**/P(odo)**

Best regards,
Chris.

**Comment by correll** [comment]
Thanks! We usually leave out the denominator as the probabilities need to be normalized anyway. In this case, it is unclear what p(odo) actually is (1?). We should add language to make this more clear.

**Comment by CL-BZH** [comment]
Thanks a lot for your answer.
Any information that can easier the life of self learner is welcome. :)
Also, I came to the conclusion that P(loc|odo)=\sum_{loc'}P(loc'->loc|odo) but I think it would be nice to clarify this as well.
